[providers]
providers = ["node"]

[variables]
PATH = "/root/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/app/node_modules/.bin:$PATH"

[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"
